defaults:
  - _self_
  - model: ???
  - override hydra/launcher: swarm
  - override hydra/sweeper: sweep

experiment_name: transformers_1
notes: |
  This run is to evaluate the neural learning quantifiers and logging in MLFlow.

tracking:
  mlflow: true
  max_retries: 8
  backoff_factor: 60
  host: 127.0.0.1
  port: 5000

expressions:
  n_limit: 2000
  output_dir: learn_quant/outputs/
  grammar:
    depth: 5
    path: learn_quant/grammar.yml
    indices: false
    index_weight: 2.0
  universe:
    x_size: 4
    m_size: 4
  representation: one_hot
  downsampling: true
  generation_args:
    batch_size: 1000
    n_limit: 5000 # Minimum number of sample rows in dataset for a single class. Full dataset length is 2 * n_limit.
    M_size: 12
    X_size: 16
    entropy_threshold: 0.01
    inclusive: False
  batch_size: 64
  split: 0.8
  target: "M${expressions.universe.m_size}/X${expressions.universe.x_size}/d${expressions.grammar.depth}"

training:
  strategy: multirun
  k_splits: 5
  n_runs: 1
  lightning: true
  device: cpu
  epochs: 50
  conditions: false
  early_stopping:
    threshold: 0.05
    monitor: val_loss
    min_delta: 0.001
    patience: 20
    mode: min
    check_on_train_epoch_end: false

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 1e-3

criterion:
  _target_: torch.nn.BCEWithLogitsLoss

measures:
  target: "M${expressions.universe.m_size}/X${expressions.universe.x_size}/d${expressions.grammar.depth}"
  monotonicity:
    debug: false
    direction:
      - all
    universe_filter:
      - 3
      - 4