defaults:
  - _self_
  - model: ???

experiment_name: learn_quant_e50
notes: |
  This run is to evaluate the neural learning quantifiers and logging in MLFlow.

tracking:
  mlflow: true
  host: n3143
  port: 5000

expressions:
  n_limit: 10000
  output_dir: learn_quant/outputs/
  grammar:
    path: learn_quant/grammar.yml
    indices: false
    index_weight: 2.0
    depth: 3
  universe:
    x_size: 4
    m_size: 4
  representation: one_hot
  downsampling: true
  generation_args:
    batch_size: 1000
    n_limit: 5000 # Minimum number of sample rows in dataset for a single class. Full dataset length is 2 * n_limit.
    M_size: 12
    X_size: 16
    entropy_threshold: 0.01
    inclusive: False
  batch_size: 64
  split: 0.8

training:
  strategy: multirun
  k_splits: 5
  n_runs: 1
  lightning: true
  device: cpu
  epochs: 100
  conditions: false
  early_stopping:
    threshold: 0.05
    monitor: val_loss
    min_delta: 0.001
    patience: 20
    mode: min
    check_on_train_epoch_end: false

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 1e-3

criterion:
  _target_: torch.nn.BCEWithLogitsLoss

measures:
  target: "M${universe.m_size}/X${universe.x_size}/d${expressions.depth}"
  monotonicity:
    debug: false
    direction:
      - all
    universe_filter:
      - 3
      - 4