import pandas as pd

from altk.language.semantics import Meaning

from ..grammar import indefinites_grammar
from ..meaning import universe as indefinites_universe
from ..util import read_expressions, read_natural_languages

if __name__ == "__main__":
    natural_languages = read_natural_languages(
        "indefinites/data/natural_language_indefinites.csv"
    )
    _, expressions_by_meaning = read_expressions(
        "indefinites/outputs/generated_expressions.yml", universe=indefinites_universe
    )
    # Verify that all NL meanings have been generated by the grammar, so that we can
    # in fact use description length to measure complexity
    assert all(
        expression.meaning in expressions_by_meaning
        for language in natural_languages
        for expression in language
    )

