import pandas as pd

from altk.language.semantics import Meaning

from ..grammar import indefinites_grammar
from ..meaning import universe as indefinites_universe

lang_data = pd.read_csv("indefinites/data/natural_language_indefinites.csv")
lang_data["flavors"] = lang_data.apply(lambda row: row[row == True].index.tolist(), axis=1)

meanings_by_description = indefinites_grammar.get_unique_expressions(
    3,
    max_size=2 ** len(indefinites_universe),
    unique_key=lambda expr: expr.evaluate(indefinites_universe),
    compare_func=lambda e1, e2: len(e1) < len(e2),
)

# get all Meanings from natural language indefinites, and verify that they are
# generated by the grammar in at most 3 steps (i.e. from the above call)
print(all(
    Meaning([indefinites_universe[flavor] for flavor in flavor_list], indefinites_universe) in meanings_by_description
    for flavor_list in lang_data["flavors"]
))
