name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: uv sync --group dev
      - name: Test with pytest
        run: uv run pytest src/tests/
